name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [windows-2016, ubuntu-16.04, macos-10.15]
          py: [3.6, 3.7, 3.8]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Install build requirements
        run: pip install -r requirements.txt

      - name: Build wheel
        run: python setup.py sdist bdist_wheel

      - name: Test wheel
        run: |
          pip install --no-index --find-links=./dist pyswmm
          pytest

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/pyswmm-*.*
